services:
  - type: web
    name: tools-module-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tools-module-db
          property: connectionString
      - key: PORT
        value: 8000

databases:
  - name: tools-module-db
    plan: free

